dist: bionic
language: ruby
rvm: 2.7
cache:
  bundler: true
before_script:
  - pip3 install matplotlib
  - bundle exec ruby ext/prophet/extconf.rb
script: bundle exec rake test
notifications:
  email:
    on_success: never
    on_failure: change
